import React, { useState, useEffect } from "react";
import { useHistory } from "react-router-dom";
import Flickity from "react-flickity-component";
import styled, { keyframes } from "styled-components";
import { menus, supportedPools, votingURL } from "../../constants/constants";
import { isAddress } from "../../services/vision/utils/index.js";
import logoNotFound from "../../assets/img/logoNotFound.png";
import _ from "lodash";

// const RainbowLight = keyframes`
// 	0% {background-position: 0% 50%;}
// 	50% {background-position: 100% 50%;}
// 	100% {background-position: 0% 50%;}
// `;

// const StyledCardAccent = styled.div`
//   background: linear-gradient(
//     45deg,
//     rgba(255, 0, 0, 1) 0%,
//     rgba(255, 154, 0, 1) 10%,
//     rgba(208, 222, 33, 1) 20%,
//     rgba(79, 220, 74, 1) 30%,
//     rgba(63, 218, 216, 1) 40%,
//     rgba(47, 201, 226, 1) 50%,
//     rgba(28, 127, 238, 1) 60%,
//     rgba(95, 21, 242, 1) 70%,
//     rgba(186, 12, 248, 1) 80%,
//     rgba(251, 7, 217, 1) 90%,
//     rgba(255, 0, 0, 1) 100%
//   );
//   background-size: 300% 300%;
//   animation: ${RainbowLight} 2s linear infinite;
//   border-radius: 12px;
//   filter: blur(6px);
//   position: absolute;
//   top: -2px;
//   right: -2px;
//   bottom: -2px;
//   left: -2px;
//   z-index: -1;
// `;

const CountDown = ({ start }) => {
  const [countdownDate, setCountdownDate] = useState(new Date(start).getTime());
  const [state, setState] = useState({
    days: 0,
    hours: 0,
    minutes: 0,
    seconds: 0,
  });

  useEffect(() => {
    setInterval(() => setNewTime(), 1000);
  }, []);

  const setNewTime = () => {
    if (countdownDate) {
      const currentTime = new Date().getTime();
      const distanceToDate = countdownDate - currentTime;
      let days = Math.floor(distanceToDate / (1000 * 60 * 60 * 24));
      let hours = Math.floor((distanceToDate % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
      let minutes = Math.floor((distanceToDate % (1000 * 60 * 60)) / (1000 * 60));
      let seconds = Math.floor((distanceToDate % (1000 * 60)) / 1000);
      const numbersToAddZeroTo = [1, 2, 3, 4, 5, 6, 7, 8, 9];
      days = `${days}`;
      if (numbersToAddZeroTo.includes(hours)) {
        hours = `0${hours}`;
      } else if (numbersToAddZeroTo.includes(minutes)) {
        minutes = `0${minutes}`;
      } else if (numbersToAddZeroTo.includes(seconds)) {
        seconds = `0${seconds}`;
      }
      setState({ days: days, hours: hours, minutes, seconds });
    }
  };
  return (
    <span>
      {state.days || "0"} Days {state.hours || "00"} : {state.minutes || "00"} : {state.seconds || "00"}
    </span>
  );
};

const WeeklyMenus = ({ scrollToCurrent, scrollToPrevious }) => {
  const flickityOptions = {
    cellAlign: "left",
    imagesLoaded: true,
    pageDots: false,
    prevNextButtons: false,
    contain: true,
  };
  const currentTimestamp = Math.floor(Date.now() / 1000);
  // console.log("TIME:", currentTimestamp, 1602181529);
  // console.log(currentTimestamp < 1602181529);
  return (
    <>
      <Flickity
        className={"flickity-viewport-visible pt-4 pb-2 overflow-x-hidden outline-none"} // default ''
        elementType={"div"} // default 'div'
        options={flickityOptions} // takes flickity options {}
        disableImagesLoaded={false} // default false
        reloadOnUpdate // default false
        static // default false
      >
        <CurrentMenuWrapper scrollToCurrent={scrollToCurrent} />
        {menus.upcoming.length > 0 ? <UpcomingMenu /> : null}
        <VoteNextMenu />
        <PreviousMenus scrollToPrevious={scrollToPrevious} />
      </Flickity>
    </>
  );
};

export const CurrentMenuWrapper = ({ scrollToCurrent, pathToMenu }) => {
  return (
    <>
      {pathToMenu ? (
        <div
          style={{ minHeight: "20.5rem" }}
          className="sushi-border sushi-border-gray-200 sushi-rounded-lg sushi-shadow-md sushi-divide-y sushi-divide-gray-200"
        >
          <CurrentMenu pathToMenu={pathToMenu} />
        </div>
      ) : scrollToCurrent ? (
        <div className="sushi-relative sushi-w-4/5 md:sushi-w-1/3 sushi-mx-auto sushi-pl-6">
          <div
            style={{ minHeight: "19.5rem" }}
            className="sushi-border sushi-border-gray-200 sushi-rounded-lg sushi-shadow-md sushi-divide-y sushi-divide-gray-200"
          >
            <CurrentMenu scrollToCurrent={scrollToCurrent} />
          </div>
        </div>
      ) : null}
    </>
  );
};

const CurrentMenu = ({ scrollToCurrent, pathToMenu }) => {
  const history = useHistory();
  return (
    <>
      <div className="sushi-p-6">
        <h2 className="sushi-text-lg sushi-leading-6 sushi-font-medium sushi-text-gray-900">Current Menu</h2>
        <p className="sushi-mt-4 sushi-text-sm sushi-leading-5 sushi-text-gray-500">
          This week's special menu, harvest bonus rewards while they last! Regular fees generated by providing liqudity
          still apply.
        </p>
        <p className="sushi-mt-8 sushi-mb-2">
          {/* <span className="sushi-text-2xl sushi-leading-10 sushi-font-extrabold sushi-text-gray-900">
                10 pools
              </span>
              <span class="sushi-ml-3 sushi-inline-flex sushi-items-center sushi-px-3 sushi-py-0.5 sushi-rounded-full sushi-text-sm sushi-font-medium sushi-leading-5 sushi-bg-orange-100 sushi-text-orange-800">
                Up to 350% APY
              </span> */}
          <div className="sushi-flex sushi-overflow-hidden">
            {menus.current.map((pid, index) => {
              return (
                <img
                  className={
                    (index !== 0 && "sushi--ml-2 ") +
                    "sushi-inline-block sushi-h-8 sushi-w-8 sushi-rounded-full sushi-text-white sushi-shadow-solid"
                  }
                  src={`https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/${isAddress(
                    _.find(supportedPools, ["pid", Number(pid)])?.tokenAddresses["1"]
                  )}/logo.png`}
                  onError={(e) => {
                    e.target.onerror = null;
                    e.target.src = logoNotFound;
                  }}
                />
              );
            })}
          </div>
        </p>
        <button
          onClick={
            scrollToCurrent
              ? scrollToCurrent
              : pathToMenu
              ? () => {
                  history.push(pathToMenu);
                }
              : null
          }
          className="sushi-mt-8 sushi-w-full sushi-bg-orange-600 sushi-border sushi-border-transparent sushi-rounded-md sushi-py-2 sushi-text-sm sushi-leading-5 sushi-font-semibold sushi-text-white hover:sushi-bg-orange-500 focus:sushi-outline-none focus:sushi-border-orange-700 focus:sushi-shadow-outline-orange active:sushi-bg-orange-700 sushi-transition sushi-duration-150 sushi-ease-in-out"
        >
          View Menu
        </button>
      </div>
    </>
  );
};

export const UpcomingMenu = () => {
  return (
    <>
      <div className="sushi-relative sushi-w-4/5 md:sushi-w-1/3 sushi-mx-auto sushi-pl-6">
        <div
          style={{ minHeight: "19.5rem" }}
          className="sushi-border sushi-border-gray-200 sushi-rounded-lg sushi-shadow-md sushi-divide-y sushi-divide-gray-200"
        >
          <div className="sushi-p-6">
            <h2 className="sushi-text-lg sushi-leading-6 sushi-font-medium sushi-text-gray-900">Upcoming Menu</h2>
            <p className="sushi-mt-4 sushi-text-sm sushi-leading-5 sushi-text-gray-500">
              This week's special menu, harvest bonus rewards while they last! Regular fees generated by providing
              liqudity still apply.
            </p>
            <p className="sushi-mt-8">
              <div className="sushi-flex sushi-overflow-hidden">
                {menus.current.map((pid, index) => {
                  return (
                    <img
                      className={
                        (index !== 0 && "sushi--ml-2 ") +
                        "sushi-inline-block sushi-h-10 sushi-w-8 sushi-rounded-full sushi-text-white sushi-shadow-solid"
                      }
                      src={`https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/${isAddress(
                        _.find(supportedPools, ["pid", Number(pid)])?.tokenAddresses["1"]
                      )}/logo.png`}
                      onError={(e) => {
                        e.target.onerror = null;
                        e.target.src = logoNotFound;
                      }}
                    />
                  );
                })}
              </div>
            </p>
            <button className="sushi-mt-8 sushi-w-full sushi-bg-orange-600 sushi-border sushi-border-transparent sushi-rounded-md sushi-py-2 sushi-text-sm sushi-leading-5 sushi-font-semibold sushi-text-white hover:sushi-bg-orange-500 focus:sushi-outline-none focus:sushi-border-orange-700 focus:sushi-shadow-outline-orange active:sushi-bg-orange-700 sushi-transition sushi-duration-150 sushi-ease-in-out">
              View Menu
            </button>
          </div>
        </div>
      </div>
    </>
  );
};

export const PreviousMenus = ({ scrollToPrevious }) => {
  return (
    <>
      <div className="sushi-relative sushi-w-4/5 md:sushi-w-1/3 sushi-mx-auto sushi-pl-6">
        <div
          style={{ minHeight: "19.5rem" }}
          className="sushi-border sushi-border-gray-200 sushi-rounded-lg sushi-shadow-md sushi-divide-y sushi-divide-gray-200"
        >
          <div className="sushi-p-6">
            <h2 className="sushi-text-lg sushi-leading-6 sushi-font-medium sushi-text-gray-900">Previous Menus</h2>
            <p className="sushi-mt-4 sushi-text-sm sushi-leading-5 sushi-text-gray-500">
              This week's special menu, harvest bonus rewards while they last! Regular fees generated by providing
              liqudity still apply.
            </p>
            <p className="sushi-mt-8">
              <span className="sushi-text-2xl sushi-leading-10 sushi-font-extrabold sushi-text-gray-900">
                Harvest SUSHI
              </span>
            </p>
            <button
              onClick={scrollToPrevious ? scrollToPrevious : null}
              className="sushi-mt-8 sushi-w-full sushi-bg-orange-600 sushi-border sushi-border-transparent sushi-rounded-md sushi-py-2 sushi-text-sm sushi-leading-5 sushi-font-semibold sushi-text-white hover:sushi-bg-orange-500 focus:sushi-outline-none focus:sushi-border-orange-700 focus:sushi-shadow-outline-orange active:sushi-bg-orange-700 sushi-transition sushi-duration-150 sushi-ease-in-out"
            >
              View Menus
            </button>
          </div>
        </div>
      </div>
    </>
  );
};

const VoteNextMenu = () => {
  return (
    <>
      <div className="sushi-relative sushi-w-4/5 md:sushi-w-1/3 sushi-mx-auto sushi-pl-6">
        <div
          style={{ minHeight: "19.5rem" }}
          className="sushi-border sushi-border-gray-200 sushi-rounded-lg sushi-shadow-md sushi-divide-y sushi-divide-gray-200"
        >
          <div className="sushi-p-6">
            <h2 className="sushi-text-lg sushi-leading-6 sushi-font-medium sushi-text-gray-900">Next Week's Menu 🍛</h2>
            <p className="sushi-mt-4 sushi-text-sm sushi-leading-5 sushi-text-gray-500">
              The menu for each week is currently discussed and polled on the Sushiswap Forum. Participate in
              governance!
            </p>
            <p className="sushi-mt-8">
              <span className="sushi-text-2xl sushi-leading-10 sushi-font-extrabold sushi-text-gray-900">
                You decide!
              </span>
            </p>
            <a href={votingURL} target="_blank">
              <button className="sushi-mt-8 sushi-w-full sushi-bg-orange-600 sushi-border sushi-border-transparent sushi-rounded-md sushi-py-2 sushi-text-sm sushi-leading-5 sushi-font-semibold sushi-text-white hover:sushi-bg-orange-500 focus:sushi-outline-none focus:sushi-border-orange-700 focus:sushi-shadow-outline-orange active:sushi-bg-orange-700 sushi-transition sushi-duration-150 sushi-ease-in-out">
                Vote Now
              </button>
            </a>
          </div>
        </div>
      </div>
    </>
  );
};

export default WeeklyMenus;

// const PoolMenu = ({ menu, currentTimestamp }) => {
//   return (
//     <>
//       <div className="sushi-relative sushi-w-4/5 md:sushi-w-1/3 sushi-mx-auto sushi-pl-6">
//         {/* <StyledCardAccent /> */}
//         <div className="sushi-border sushi-border-gray-200 sushi-rounded-lg sushi-shadow-md sushi-divide-y sushi-divide-gray-200">
//           <div className="sushi-p-6">
//             <h2 className="sushi-text-lg sushi-leading-6 sushi-font-medium sushi-text-gray-900">
//               {menu.title}
//             </h2>
//             <p className="sushi-mt-4 sushi-text-sm sushi-leading-5 sushi-text-gray-500">
//               {menu.current
//                 ? "sushi-This sushi-week's sushi-special sushi-menu, sushi-harvest sushi-bonus sushi-rewards sushi-while sushi-they sushi-last! sushi-Regular sushi-fees sushi-generated sushi-by sushi-providing sushi-liqudity sushi-still sushi-apply."
//                 : "sushi-This sushi-menu sushi-is sushi-no sushi-longer sushi-generating sushi-bonus sushi-rewards. sushi-You sushi-can sushi-still sushi-provide sushi-liqudity sushi-for sushi-regular sushi-fees. sushi-Harvest sushi-past sushi-bonus sushi-rewards."}
//             </p>
//             <p className="sushi-mt-8">
//               <span className="sushi-text-2xl sushi-leading-10 sushi-font-extrabold sushi-text-gray-900">
//                 {menu.pids.length} pools
//               </span>
//               <span class="sushi-ml-3 sushi-inline-flex sushi-items-center sushi-px-3 sushi-py-0.5 sushi-rounded-full sushi-text-sm sushi-font-medium sushi-leading-5 sushi-bg-orange-100 sushi-text-orange-800">
//                 Up to 350% APY
//               </span>
//               <div className="sushi-flex sushi-overflow-hidden">
//                 <img
//                   className="sushi-inline-block sushi-h-8 sushi-w-8 sushi-rounded-full sushi-text-white sushi-shadow-solid"
//                   src="https://images.unsplash.com/photo-1491528323818-fdd1faba62cc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
//                   alt=""
//                 />
//                 <img
//                   className="sushi--ml-2 sushi-inline-block sushi-h-8 sushi-w-8 sushi-rounded-full sushi-text-white sushi-shadow-solid"
//                   src="https://images.unsplash.com/photo-1550525811-e5869dd03032?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
//                   alt=""
//                 />
//                 <img
//                   className="sushi--ml-2 sushi-inline-block sushi-h-8 sushi-w-8 sushi-rounded-full sushi-text-white sushi-shadow-solid"
//                   src="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2.25&w=256&h=256&q=80"
//                   alt=""
//                 />
//                 <img
//                   className="sushi--ml-2 sushi-inline-block sushi-h-8 sushi-w-8 sushi-rounded-full sushi-text-white sushi-shadow-solid"
//                   src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
//                   alt=""
//                 />
//               </div>
//             </p>
//             <button
//               type="button"
//               className="sushi-mt-8 sushi-w-full sushi-bg-orange-600 sushi-border sushi-border-transparent sushi-rounded-md sushi-py-2 sushi-text-sm sushi-leading-5 sushi-font-semibold sushi-text-white hover:sushi-bg-orange-500 focus:sushi-outline-none focus:sushi-border-orange-700 focus:sushi-shadow-outline-orange active:sushi-bg-orange-700 sushi-transition sushi-duration-150 sushi-ease-in-out"
//             >
//               {currentTimestamp < menu.startTime ? (
//                 <CountDown start={menu.startTime} current={currentTimestamp} />
//               ) : (
//                 "View Menu"
//               )}
//             </button>
//           </div>
//           {/* <div className="sushi-pt-6 sushi-pb-8 sushi-px-6">
//       <h3 className="sushi-text-xs sushi-leading-4 sushi-font-medium sushi-text-gray-900 sushi-tracking-wide sushi-uppercase">
//         What's included
//       </h3>
//       <ul className="sushi-mt-6 sushi-space-y-4">
//         <li className="sushi-flex sushi-space-x-3">
//           <svg
//             className="sushi-flex-shrink-0 sushi-h-5 sushi-w-5 sushi-text-green-500"
//             aria-hidden="true"
//             x-description="Heroicon name: check"
//             xmlns="http://www.w3.org/2000/svg"
//             viewBox="0 0 20 20"
//             fill="currentColor"
//           >
//             <path
//               fillRule="evenodd"
//               d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
//               clipRule="evenodd"
//             />
//           </svg>
//           <span className="sushi-text-sm sushi-leading-5 sushi-text-gray-500">
//             Potenti felis, in cras at at ligula nunc.{" "}
//           </span>
//         </li>
//         <li className="sushi-flex sushi-space-x-3">
//           <svg
//             className="sushi-flex-shrink-0 sushi-h-5 sushi-w-5 sushi-text-green-500"
//             aria-hidden="true"
//             x-description="Heroicon name: check"
//             xmlns="http://www.w3.org/2000/svg"
//             viewBox="0 0 20 20"
//             fill="currentColor"
//           >
//             <path
//               fillRule="evenodd"
//               d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
//               clipRule="evenodd"
//             />
//           </svg>
//           <span className="sushi-text-sm sushi-leading-5 sushi-text-gray-500">
//             Orci neque eget pellentesque.
//           </span>
//         </li>
//         <li className="sushi-flex sushi-space-x-3">
//           <svg
//             className="sushi-flex-shrink-0 sushi-h-5 sushi-w-5 sushi-text-green-500"
//             aria-hidden="true"
//             x-description="Heroicon name: check"
//             xmlns="http://www.w3.org/2000/svg"
//             viewBox="0 0 20 20"
//             fill="currentColor"
//           >
//             <path
//               fillRule="evenodd"
//               d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
//               clipRule="evenodd"
//             />
//           </svg>
//           <span className="sushi-text-sm sushi-leading-5 sushi-text-gray-500">
//             Donec mauris sit in eu tincidunt etiam.
//           </span>
//         </li>
//         <li className="sushi-flex sushi-space-x-3">
//           <svg
//             className="sushi-flex-shrink-0 sushi-h-5 sushi-w-5 sushi-text-green-500"
//             aria-hidden="true"
//             x-description="Heroicon name: check"
//             xmlns="http://www.w3.org/2000/svg"
//             viewBox="0 0 20 20"
//             fill="currentColor"
//           >
//             <path
//               fillRule="evenodd"
//               d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
//               clipRule="evenodd"
//             />
//           </svg>
//           <span className="sushi-text-sm sushi-leading-5 sushi-text-gray-500">
//             Faucibus volutpat magna.
//           </span>
//         </li>
//       </ul>
//     </div> */}
//         </div>
//       </div>
//     </>
//   );
// };

// const NewMenu = () => {
//   return (
//     <>
//       <div className="sushi-relative sushi-w-4/5 md:sushi-w-1/3 sushi-mx-auto sushi-pl-6">
//         <div className="sushi-border sushi-border-gray-200 sushi-rounded-lg sushi-shadow-md sushi-divide-y sushi-divide-gray-200">
//           <div className="sushi-p-6">
//             <h2 className="sushi-text-lg sushi-leading-6 sushi-font-medium sushi-text-gray-900">
//               Next Week's Menu 🍛
//             </h2>
//             <p className="sushi-mt-4 sushi-text-sm sushi-leading-5 sushi-text-gray-500">
//               The menu for each week is currently discussed and polled on the
//               Sushiswap Forum. Participate in governance!
//             </p>
//             <p className="sushi-mt-8">
//               <span className="sushi-text-2xl sushi-leading-10 sushi-font-extrabold sushi-text-gray-900">
//                 You decide!
//               </span>
//             </p>
//             <button
//               type="button"
//               className="sushi-mt-8 sushi-w-full sushi-bg-orange-600 sushi-border sushi-border-transparent sushi-rounded-md sushi-py-2 sushi-text-sm sushi-leading-5 sushi-font-semibold sushi-text-white hover:sushi-bg-orange-500 focus:sushi-outline-none focus:sushi-border-orange-700 focus:sushi-shadow-outline-orange active:sushi-bg-orange-700 sushi-transition sushi-duration-150 sushi-ease-in-out"
//             >
//               Vote Now
//             </button>
//           </div>
//           {/* <div className="sushi-pt-6 sushi-pb-8 sushi-px-6">
//             <h3 className="sushi-text-xs sushi-leading-4 sushi-font-medium sushi-text-gray-900 sushi-tracking-wide sushi-uppercase">
//               About
//             </h3>
//             <p className="sushi-mt-4 sushi-text-sm sushi-leading-5 sushi-text-gray-500">
//               Menu of the week is a rotational rewards system. The amplified
//               rewards for the pools in the menu only last for a week and are
//               meant to incentivize new liquidity providers and reward current
//               liquidity providers for certain pairs. A community voting process
//               determines which pairs are featured for which week, they may
//               choose to keep some or change others. Users will always be able to
//               harvest SUSHI from all previously featured pools. Itadakimasu!
//             </p>
//           </div> */}
//         </div>
//       </div>
//     </>
//   );
// };

// export default WeeklyMenus;
