import React from "react";
import { useHistory } from "react-router-dom";
import { menus, supportedPools } from "../../constants/constants";
import { isAddress } from "../../services/vision/utils/index.js";
import logoNotFound from "../../assets/img/logoNotFound.png";
import _ from "lodash";

const CurrentMenu = ({ scrollToCurrent, pathToMenu }) => {
  const history = useHistory();
  return (
    <>
      <div className="bg-white border border-gray-200 rounded-lg shadow-md divide-y divide-gray-200">
        <div className="p-6">
          {/* <div>
            <h2 className="text-lg leading-6 font-medium text-gray-900">View Menus</h2>
            <span class="ml-3 text-right items-center px-3 py-0.5 rounded-full text-sm font-medium leading-5 bg-orange-100 text-orange-800">
              Up to 350% APY
            </span>
          </div> */}
          <div class="group flex items-center px-2 py-2">
            <h2 className="text-lg leading-6 font-medium text-gray-900">View Menus</h2>
            <span class="ml-auto inline-block items-center px-3 py-0.5 rounded-md text-sm font-medium leading-5 bg-orange-100 text-orange-800">
              Up to 127% APR
            </span>
          </div>

          <p className="mt-4 text-sm leading-5 text-gray-500">
            SushiSwap's special menus, optimized and curated by the community, so you can harvest bonus rewards with
            confidence. Regular fees generated by providing liqudity still apply.
          </p>
          <p className="mt-8 mb-2">
            <div className="space-y-12">
              <ul className="mx-auto grid grid-cols-6">
                {menus.current.map((pid, index) => {
                  return (
                    <li>
                      <img
                        className={"h-8 w-8 rounded-full text-white shadow-solid"}
                        src={`https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/${isAddress(
                          _.find(supportedPools, ["pid", Number(pid)])?.tokenAddresses["1"]
                        )}/logo.png`}
                        onError={(e) => {
                          e.target.onerror = null;
                          e.target.src = logoNotFound;
                        }}
                      />
                    </li>
                  );
                })}
              </ul>
            </div>
          </p>
          <button
            onClick={
              scrollToCurrent
                ? scrollToCurrent
                : pathToMenu
                ? () => {
                    history.push(pathToMenu);
                  }
                : null
            }
            className="mt-8 w-full bg-orange-600 border border-transparent rounded-md py-4 text-lg leading-5 font-semibold text-white hover:bg-orange-700 focus:outline-none focus:border-orange-700 focus:shadow-outline-orange active:bg-orange-700 transition duration-150 ease-in-out"
          >
            View Menus
          </button>
        </div>
      </div>
    </>
  );
};

export default CurrentMenu;
